language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install pep8 pyflakes
script:
  - python tests.py
before_script:
  - "pep8 parametrized"
  - pyflakes parametrized
